### ISSUE TITLE
Changes to work on 6.4.0 Beta Load19

### ISSUE THREAD

**Issue by schaefa** [nateyolles/aem-clientlib-async#4]
Hi

In order to make the ClientLibUseObject work on 6.4.0 Beta Load 19 I have to change some imports to:

import org.apache.sling.scripting.sightly.pojo.Use;
import com.adobe.granite.ui.clientlibs.ClientLibrary;
import com.adobe.granite.ui.clientlibs.HtmlLibraryManager;
import com.adobe.granite.ui.clientlibs.LibraryType;

and remove the old ones. Afterwards the deployment works just fine.

**Comment by susheel61** [comment]
But still dependencies are not getting added on to the page.

**Comment by nateyolles** [comment]
We've updated com.day.cq.widget.* to com.adobe.granite.ui.clientlibs.* and com.adobe.granite.xss.XSSAPI to
org.apache.sling.xss.XSSAPI. Thank you.
