### ISSUE TITLE
Imcompatible with ACS Commons Versioned Clientlibs feature

### ISSUE THREAD

**Issue by fernandohu** [nateyolles/aem-clientlib-async#6]
I am working on a project that uses your code and I found a problem.

It is not possible to use the Versioned Clientlib feature of ACS Commons.

The version hashes are not appended to the end of the JS and CSS urls.

**Comment by fernandohu** [comment]
Hi. I found a solution for this, that is described in this page: https://forums.adobe.com/thread/2613261

In summary, you have to add the type attribute to CSS and JS import. You can do that in the ClientLibUseObject.java java file. If you do that, the Versioned Clientlibs feature will work correctly.

**Comment by nateyolles** [comment]
We've added the type attribute for both the script and the link elements. Thank you @fernandohu.
