### ISSUE TITLE
Multiple of same component loads files more than once.

### ISSUE THREAD

**Issue by Nekramess** [nateyolles/aem-clientlib-async#7]
With the Client Libs out of the box if I include a component on the page more than once it will only load css/js one time, but when trying to use this for defer it is loading css/js files for each of the components.

This is the way I was loading css/js before

`<sly data-sly-use.clientLib="/libs/granite/sightly/templates/clientlib.html"
     data-sly-call="${clientlib.all @ categories='MarketGlobal.component.pagetitle'}">
</sly>`

This is the way I am loading it now.
`<sly data-sly-use.clientLib="/apps/clientlib-async/sightly/templates/clientlib.html"
     data-sly-call="${clientlib.js @ categories='MarketGlobal.component.pagetitle.jp' , loading='defer'}">
</sly>`

`<sly data-sly-use.clientLib="/apps/clientlib-async/sightly/templates/clientlib.html"
     data-sly-call="${clientlib.css @ categories='MarketGlobal.component.pagetitle.jp'}">
</sly>`

We load the css/js directly into the Component instead of loading them into one giant file. When the page renders out I can see it making a css/js for each time I add the pagetitle to the screen. I will investigate this but Thought I would open a issue so you would be aware of it. Thanks for this awesome library it is working great so far.

**Comment by Nekramess** [comment]
We solved this by adding these 2 functions 


private Set<String> getIncludedSet(SlingHttpServletRequest request)
    {
        Set<String> set = (Set)request.getAttribute(INCLUDED_SET_ATTR_NAME);
        if (set == null) {
            set = new HashSet();
            request.setAttribute(INCLUDED_SET_ATTR_NAME, set);
        }
        return set;
    }
    private boolean isIncluded(SlingHttpServletRequest request, String path)
    {
        if (path == null) {
            return true;
        }
        Set<String> set = getIncludedSet(request);
        if (set.contains(path)) {
            return true;
        }
        set.add(path);
        return false;
    }


and modifying the includedLibraries method to check for isIncluded

if (path != null) {
                    if(!isIncluded(request,path)){
                        out.format(libraryType.equals(LibraryType.JS) ? TAG_JAVASCRIPT : TAG_STYLESHEET, path, attribute);
                    }
                }

**Comment by sanderlenaerts** [comment]
@aharris12 @nateyolles shouldn't this be added by default?
